/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "algorithm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(algoPkg_humanDetectionMsg, algoPkg_humanDetectionMsg, AUTO)


PB_BIND(algoPkg_blobDetectionMsg, algoPkg_blobDetectionMsg, AUTO)


PB_BIND(algoPkg_hdConfigMsg, algoPkg_hdConfigMsg, AUTO)


PB_BIND(algoPkg_algoMsg, algoPkg_algoMsg, AUTO)



