/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "backpack-config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(backpackConfigPkg_channelConfigMsg, backpackConfigPkg_channelConfigMsg, AUTO)


PB_BIND(backpackConfigPkg_channelsConfigMsg, backpackConfigPkg_channelsConfigMsg, AUTO)



