/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "backpack.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(backpackPkg_backpackDevInfo, backpackPkg_backpackDevInfo, AUTO)


PB_BIND(backpackPkg_backpackMsg, backpackPkg_backpackMsg, 2)




