/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_BLECENTRALPKG_BLE_CENTRAL_PB_H_INCLUDED
#define PB_BLECENTRALPKG_BLE_CENTRAL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* ******************************************************************************
  BLE CENTRAL MESSENGER
****************************************************************************** */
typedef struct _bleCentralPkg_bleDevInfo {
    uint64_t address;
    uint32_t addrType;
} bleCentralPkg_bleDevInfo;

typedef struct _bleCentralPkg_bleDevsInfo {
    pb_size_t list_count;
    bleCentralPkg_bleDevInfo list[20];
} bleCentralPkg_bleDevsInfo;

typedef struct _bleCentralPkg_bleCentralMsg {
    pb_size_t which_type;
    union {
        pb_callback_t state;
        bleCentralPkg_bleDevsInfo scanDev;
        bleCentralPkg_bleDevsInfo connectDev;
        bleCentralPkg_bleDevsInfo reqConnectDev;
        bleCentralPkg_bleDevsInfo reqDisconnectDev;
        bool listConnectedDev;
    } type;
} bleCentralPkg_bleCentralMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define bleCentralPkg_bleDevInfo_init_default    {0, 0}
#define bleCentralPkg_bleDevsInfo_init_default   {0, {bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default, bleCentralPkg_bleDevInfo_init_default}}
#define bleCentralPkg_bleCentralMsg_init_default {0, {{{NULL}, NULL}}}
#define bleCentralPkg_bleDevInfo_init_zero       {0, 0}
#define bleCentralPkg_bleDevsInfo_init_zero      {0, {bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero, bleCentralPkg_bleDevInfo_init_zero}}
#define bleCentralPkg_bleCentralMsg_init_zero    {0, {{{NULL}, NULL}}}

/* Field tags (for use in manual encoding/decoding) */
#define bleCentralPkg_bleDevInfo_address_tag     1
#define bleCentralPkg_bleDevInfo_addrType_tag    2
#define bleCentralPkg_bleDevsInfo_list_tag       1
#define bleCentralPkg_bleCentralMsg_state_tag    1
#define bleCentralPkg_bleCentralMsg_scanDev_tag  2
#define bleCentralPkg_bleCentralMsg_connectDev_tag 3
#define bleCentralPkg_bleCentralMsg_reqConnectDev_tag 10
#define bleCentralPkg_bleCentralMsg_reqDisconnectDev_tag 11
#define bleCentralPkg_bleCentralMsg_listConnectedDev_tag 12

/* Struct field encoding specification for nanopb */
#define bleCentralPkg_bleDevInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   address,           1) \
X(a, STATIC,   SINGULAR, UINT32,   addrType,          2)
#define bleCentralPkg_bleDevInfo_CALLBACK NULL
#define bleCentralPkg_bleDevInfo_DEFAULT NULL

#define bleCentralPkg_bleDevsInfo_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  list,              1)
#define bleCentralPkg_bleDevsInfo_CALLBACK NULL
#define bleCentralPkg_bleDevsInfo_DEFAULT NULL
#define bleCentralPkg_bleDevsInfo_list_MSGTYPE bleCentralPkg_bleDevInfo

#define bleCentralPkg_bleCentralMsg_FIELDLIST(X, a) \
X(a, CALLBACK, ONEOF,    STRING,   (type,state,type.state),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,scanDev,type.scanDev),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,connectDev,type.connectDev),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,reqConnectDev,type.reqConnectDev),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,reqDisconnectDev,type.reqDisconnectDev),  11) \
X(a, STATIC,   ONEOF,    BOOL,     (type,listConnectedDev,type.listConnectedDev),  12)
#define bleCentralPkg_bleCentralMsg_CALLBACK pb_default_field_callback
#define bleCentralPkg_bleCentralMsg_DEFAULT NULL
#define bleCentralPkg_bleCentralMsg_type_scanDev_MSGTYPE bleCentralPkg_bleDevsInfo
#define bleCentralPkg_bleCentralMsg_type_connectDev_MSGTYPE bleCentralPkg_bleDevsInfo
#define bleCentralPkg_bleCentralMsg_type_reqConnectDev_MSGTYPE bleCentralPkg_bleDevsInfo
#define bleCentralPkg_bleCentralMsg_type_reqDisconnectDev_MSGTYPE bleCentralPkg_bleDevsInfo

extern const pb_msgdesc_t bleCentralPkg_bleDevInfo_msg;
extern const pb_msgdesc_t bleCentralPkg_bleDevsInfo_msg;
extern const pb_msgdesc_t bleCentralPkg_bleCentralMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define bleCentralPkg_bleDevInfo_fields &bleCentralPkg_bleDevInfo_msg
#define bleCentralPkg_bleDevsInfo_fields &bleCentralPkg_bleDevsInfo_msg
#define bleCentralPkg_bleCentralMsg_fields &bleCentralPkg_bleCentralMsg_msg

/* Maximum encoded size of messages (where known) */
/* bleCentralPkg_bleCentralMsg_size depends on runtime parameters */
#define bleCentralPkg_bleDevInfo_size            17
#define bleCentralPkg_bleDevsInfo_size           380

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
