/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "ble-central.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(bleCentralPkg_bleDevInfo, bleCentralPkg_bleDevInfo, AUTO)


PB_BIND(bleCentralPkg_bleDevsInfo, bleCentralPkg_bleDevsInfo, AUTO)


PB_BIND(bleCentralPkg_bleCentralMsg, bleCentralPkg_bleCentralMsg, 2)



