/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "collector.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(collectorPkg_devInfo, collectorPkg_devInfo, 2)


PB_BIND(collectorPkg_startLossTestMsg, collectorPkg_startLossTestMsg, AUTO)


PB_BIND(collectorPkg_lossTestResultMsg, collectorPkg_lossTestResultMsg, AUTO)


PB_BIND(collectorPkg_lossTestProgressMsg, collectorPkg_lossTestProgressMsg, AUTO)


PB_BIND(collectorPkg_blinkMsg, collectorPkg_blinkMsg, AUTO)


PB_BIND(collectorPkg_identifyMsg, collectorPkg_identifyMsg, AUTO)


PB_BIND(collectorPkg_collectorMsg, collectorPkg_collectorMsg, 2)



