/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_COLLECTORPKG_COLLECTOR_PB_H_INCLUDED
#define PB_COLLECTORPKG_COLLECTOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* ******************************************************************************
  SUB-1GHZ COLLECTOR MESSENGER
****************************************************************************** */
typedef struct _collectorPkg_devInfo {
    pb_size_t address_count;
    uint32_t address[100];
    uint32_t addrBlockSize;
} collectorPkg_devInfo;

typedef struct _collectorPkg_startLossTestMsg {
    uint32_t packetSize;
    uint32_t packetNum;
    uint32_t period;
} collectorPkg_startLossTestMsg;

typedef struct _collectorPkg_lossTestResultMsg {
    uint32_t nodeAddr;
    uint32_t numPacketSent;
    uint32_t numPacketReceived;
    bool success;
} collectorPkg_lossTestResultMsg;

typedef struct _collectorPkg_lossTestProgressMsg {
    uint32_t packetNum;
    bool success;
} collectorPkg_lossTestProgressMsg;

typedef struct _collectorPkg_blinkMsg {
    uint32_t address;
} collectorPkg_blinkMsg;

typedef struct _collectorPkg_identifyMsg {
    uint32_t address;
} collectorPkg_identifyMsg;

typedef struct _collectorPkg_collectorMsg {
    pb_size_t which_type;
    union {
        collectorPkg_devInfo devList;
        collectorPkg_startLossTestMsg startLossTest;
        collectorPkg_lossTestResultMsg lossTestResult;
        collectorPkg_lossTestProgressMsg lossTestProgress;
        collectorPkg_identifyMsg identify;
        bool blink;
        bool reqList;
        bool reqStopLossTest;
    } type;
} collectorPkg_collectorMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define collectorPkg_devInfo_init_default        {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define collectorPkg_startLossTestMsg_init_default {0, 0, 0}
#define collectorPkg_lossTestResultMsg_init_default {0, 0, 0, 0}
#define collectorPkg_lossTestProgressMsg_init_default {0, 0}
#define collectorPkg_blinkMsg_init_default       {0}
#define collectorPkg_identifyMsg_init_default    {0}
#define collectorPkg_collectorMsg_init_default   {0, {collectorPkg_devInfo_init_default}}
#define collectorPkg_devInfo_init_zero           {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define collectorPkg_startLossTestMsg_init_zero  {0, 0, 0}
#define collectorPkg_lossTestResultMsg_init_zero {0, 0, 0, 0}
#define collectorPkg_lossTestProgressMsg_init_zero {0, 0}
#define collectorPkg_blinkMsg_init_zero          {0}
#define collectorPkg_identifyMsg_init_zero       {0}
#define collectorPkg_collectorMsg_init_zero      {0, {collectorPkg_devInfo_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define collectorPkg_devInfo_address_tag         1
#define collectorPkg_devInfo_addrBlockSize_tag   2
#define collectorPkg_startLossTestMsg_packetSize_tag 1
#define collectorPkg_startLossTestMsg_packetNum_tag 2
#define collectorPkg_startLossTestMsg_period_tag 3
#define collectorPkg_lossTestResultMsg_nodeAddr_tag 1
#define collectorPkg_lossTestResultMsg_numPacketSent_tag 2
#define collectorPkg_lossTestResultMsg_numPacketReceived_tag 3
#define collectorPkg_lossTestResultMsg_success_tag 4
#define collectorPkg_lossTestProgressMsg_packetNum_tag 1
#define collectorPkg_lossTestProgressMsg_success_tag 2
#define collectorPkg_blinkMsg_address_tag        1
#define collectorPkg_identifyMsg_address_tag     1
#define collectorPkg_collectorMsg_devList_tag    1
#define collectorPkg_collectorMsg_startLossTest_tag 2
#define collectorPkg_collectorMsg_lossTestResult_tag 3
#define collectorPkg_collectorMsg_lossTestProgress_tag 4
#define collectorPkg_collectorMsg_identify_tag   6
#define collectorPkg_collectorMsg_blink_tag      7
#define collectorPkg_collectorMsg_reqList_tag    8
#define collectorPkg_collectorMsg_reqStopLossTest_tag 9

/* Struct field encoding specification for nanopb */
#define collectorPkg_devInfo_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT32,   address,           1) \
X(a, STATIC,   SINGULAR, UINT32,   addrBlockSize,     2)
#define collectorPkg_devInfo_CALLBACK NULL
#define collectorPkg_devInfo_DEFAULT NULL

#define collectorPkg_startLossTestMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   packetSize,        1) \
X(a, STATIC,   SINGULAR, UINT32,   packetNum,         2) \
X(a, STATIC,   SINGULAR, UINT32,   period,            3)
#define collectorPkg_startLossTestMsg_CALLBACK NULL
#define collectorPkg_startLossTestMsg_DEFAULT NULL

#define collectorPkg_lossTestResultMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   nodeAddr,          1) \
X(a, STATIC,   SINGULAR, UINT32,   numPacketSent,     2) \
X(a, STATIC,   SINGULAR, UINT32,   numPacketReceived,   3) \
X(a, STATIC,   SINGULAR, BOOL,     success,           4)
#define collectorPkg_lossTestResultMsg_CALLBACK NULL
#define collectorPkg_lossTestResultMsg_DEFAULT NULL

#define collectorPkg_lossTestProgressMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   packetNum,         1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2)
#define collectorPkg_lossTestProgressMsg_CALLBACK NULL
#define collectorPkg_lossTestProgressMsg_DEFAULT NULL

#define collectorPkg_blinkMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   address,           1)
#define collectorPkg_blinkMsg_CALLBACK NULL
#define collectorPkg_blinkMsg_DEFAULT NULL

#define collectorPkg_identifyMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   address,           1)
#define collectorPkg_identifyMsg_CALLBACK NULL
#define collectorPkg_identifyMsg_DEFAULT NULL

#define collectorPkg_collectorMsg_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,devList,type.devList),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,startLossTest,type.startLossTest),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,lossTestResult,type.lossTestResult),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,lossTestProgress,type.lossTestProgress),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,identify,type.identify),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (type,blink,type.blink),   7) \
X(a, STATIC,   ONEOF,    BOOL,     (type,reqList,type.reqList),   8) \
X(a, STATIC,   ONEOF,    BOOL,     (type,reqStopLossTest,type.reqStopLossTest),   9)
#define collectorPkg_collectorMsg_CALLBACK NULL
#define collectorPkg_collectorMsg_DEFAULT NULL
#define collectorPkg_collectorMsg_type_devList_MSGTYPE collectorPkg_devInfo
#define collectorPkg_collectorMsg_type_startLossTest_MSGTYPE collectorPkg_startLossTestMsg
#define collectorPkg_collectorMsg_type_lossTestResult_MSGTYPE collectorPkg_lossTestResultMsg
#define collectorPkg_collectorMsg_type_lossTestProgress_MSGTYPE collectorPkg_lossTestProgressMsg
#define collectorPkg_collectorMsg_type_identify_MSGTYPE collectorPkg_identifyMsg

extern const pb_msgdesc_t collectorPkg_devInfo_msg;
extern const pb_msgdesc_t collectorPkg_startLossTestMsg_msg;
extern const pb_msgdesc_t collectorPkg_lossTestResultMsg_msg;
extern const pb_msgdesc_t collectorPkg_lossTestProgressMsg_msg;
extern const pb_msgdesc_t collectorPkg_blinkMsg_msg;
extern const pb_msgdesc_t collectorPkg_identifyMsg_msg;
extern const pb_msgdesc_t collectorPkg_collectorMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define collectorPkg_devInfo_fields &collectorPkg_devInfo_msg
#define collectorPkg_startLossTestMsg_fields &collectorPkg_startLossTestMsg_msg
#define collectorPkg_lossTestResultMsg_fields &collectorPkg_lossTestResultMsg_msg
#define collectorPkg_lossTestProgressMsg_fields &collectorPkg_lossTestProgressMsg_msg
#define collectorPkg_blinkMsg_fields &collectorPkg_blinkMsg_msg
#define collectorPkg_identifyMsg_fields &collectorPkg_identifyMsg_msg
#define collectorPkg_collectorMsg_fields &collectorPkg_collectorMsg_msg

/* Maximum encoded size of messages (where known) */
#define collectorPkg_blinkMsg_size               6
#define collectorPkg_collectorMsg_size           609
#define collectorPkg_devInfo_size                606
#define collectorPkg_identifyMsg_size            6
#define collectorPkg_lossTestProgressMsg_size    8
#define collectorPkg_lossTestResultMsg_size      20
#define collectorPkg_startLossTestMsg_size       18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
