/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_CMDPKG_COMMAND_PB_H_INCLUDED
#define PB_CMDPKG_COMMAND_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* ******************************************************************************
  MESSENGER
****************************************************************************** */
typedef struct _cmdPkg_writeRegMsg {
    uint32_t reg;
    uint32_t value;
} cmdPkg_writeRegMsg;

typedef struct _cmdPkg_rgbVideoModeMsg {
    uint32_t mode;
    uint32_t frameCnt;
} cmdPkg_rgbVideoModeMsg;

typedef struct _cmdPkg_autoGainRGBCamMsg {
    uint32_t enable;
    uint32_t gainDb;
    uint32_t gainDbCeiling;
} cmdPkg_autoGainRGBCamMsg;

typedef struct _cmdPkg_expouseRGBCamMsg {
    uint32_t enable;
    uint32_t exposureUs;
} cmdPkg_expouseRGBCamMsg;

typedef struct _cmdPkg_RGBCamMsg {
    pb_size_t which_type;
    union {
        uint32_t startRGBCam;
        bool stopRGBCam;
        bool captureRGBCam;
        uint32_t updateIntervalRGBCam;
        bool shutdownRGBCam;
        bool bootupRGBCam;
        bool powerOffRGBCam;
        bool powerOnRGBCam;
        bool alwaysOnModeRGBCam;
        bool optimizeModeRGBCam;
        bool runFCCRGBCam;
        bool getInfoRGBCam;
        cmdPkg_writeRegMsg writeRegRGBCam;
        uint32_t readRegRGBCam;
        cmdPkg_rgbVideoModeMsg videoModeRGBCam;
        uint32_t bightnessRGBCam;
        cmdPkg_expouseRGBCamMsg expouseRGBCam;
        cmdPkg_autoGainRGBCamMsg autoGainRGBCam;
        uint32_t gainCeilingRGBCam;
        uint32_t frameRateRGBCam;
        uint32_t pixelFormatRGBCam;
        uint32_t frameSizeRGBCam;
    } type;
} cmdPkg_RGBCamMsg;

typedef struct _cmdPkg_IRCamMsg {
    pb_size_t which_type;
    union {
        uint32_t startIrCam;
        bool stopIrCam;
        bool captureIrCam;
        uint32_t updateIntervalIrCam;
        bool shutdownIrCam;
        bool bootupIrCam;
        bool powerOffIrCam;
        bool powerOnIrCam;
        bool alwaysOnModeIrCam;
        bool optimizeModeIrCam;
        bool runFCCIrCam;
        bool getInfoIrCam;
        bool humanDetectionEnIrCam;
    } type;
} cmdPkg_IRCamMsg;

typedef struct _cmdPkg_transferControlImuMsg {
    /* bool includeImu = 1; */
    bool dimension;
    bool quaternion;
    bool imuOmega;
    bool imuAbsoluteLinearSpeed;
    bool accel;
    bool imuPosition;
    bool angularVelocity;
} cmdPkg_transferControlImuMsg;

typedef struct _cmdPkg_transferControlUwbMsg {
    /* bool includeUwb = 1; */
    bool location;
    bool ranging;
} cmdPkg_transferControlUwbMsg;

typedef struct _cmdPkg_transferControlMsg {
    bool has_imu;
    cmdPkg_transferControlImuMsg imu;
    bool has_uwb;
    cmdPkg_transferControlUwbMsg uwb;
} cmdPkg_transferControlMsg;

typedef struct _cmdPkg_cmdMsg {
    pb_size_t which_type;
    union {
        /* IR camera message */
        cmdPkg_IRCamMsg irMsg;
        /* RGB camera message */
        cmdPkg_RGBCamMsg rgbMsg;
        /* Transfer control message */
        cmdPkg_transferControlMsg transferControlCfg;
        bool transferControlGet;
    } type;
} cmdPkg_cmdMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cmdPkg_writeRegMsg_init_default          {0, 0}
#define cmdPkg_rgbVideoModeMsg_init_default      {0, 0}
#define cmdPkg_autoGainRGBCamMsg_init_default    {0, 0, 0}
#define cmdPkg_expouseRGBCamMsg_init_default     {0, 0}
#define cmdPkg_RGBCamMsg_init_default            {0, {0}}
#define cmdPkg_IRCamMsg_init_default             {0, {0}}
#define cmdPkg_transferControlImuMsg_init_default {0, 0, 0, 0, 0, 0, 0}
#define cmdPkg_transferControlUwbMsg_init_default {0, 0}
#define cmdPkg_transferControlMsg_init_default   {false, cmdPkg_transferControlImuMsg_init_default, false, cmdPkg_transferControlUwbMsg_init_default}
#define cmdPkg_cmdMsg_init_default               {0, {cmdPkg_IRCamMsg_init_default}}
#define cmdPkg_writeRegMsg_init_zero             {0, 0}
#define cmdPkg_rgbVideoModeMsg_init_zero         {0, 0}
#define cmdPkg_autoGainRGBCamMsg_init_zero       {0, 0, 0}
#define cmdPkg_expouseRGBCamMsg_init_zero        {0, 0}
#define cmdPkg_RGBCamMsg_init_zero               {0, {0}}
#define cmdPkg_IRCamMsg_init_zero                {0, {0}}
#define cmdPkg_transferControlImuMsg_init_zero   {0, 0, 0, 0, 0, 0, 0}
#define cmdPkg_transferControlUwbMsg_init_zero   {0, 0}
#define cmdPkg_transferControlMsg_init_zero      {false, cmdPkg_transferControlImuMsg_init_zero, false, cmdPkg_transferControlUwbMsg_init_zero}
#define cmdPkg_cmdMsg_init_zero                  {0, {cmdPkg_IRCamMsg_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define cmdPkg_writeRegMsg_reg_tag               1
#define cmdPkg_writeRegMsg_value_tag             2
#define cmdPkg_rgbVideoModeMsg_mode_tag          1
#define cmdPkg_rgbVideoModeMsg_frameCnt_tag      2
#define cmdPkg_autoGainRGBCamMsg_enable_tag      1
#define cmdPkg_autoGainRGBCamMsg_gainDb_tag      2
#define cmdPkg_autoGainRGBCamMsg_gainDbCeiling_tag 3
#define cmdPkg_expouseRGBCamMsg_enable_tag       1
#define cmdPkg_expouseRGBCamMsg_exposureUs_tag   2
#define cmdPkg_RGBCamMsg_startRGBCam_tag         1
#define cmdPkg_RGBCamMsg_stopRGBCam_tag          2
#define cmdPkg_RGBCamMsg_captureRGBCam_tag       3
#define cmdPkg_RGBCamMsg_updateIntervalRGBCam_tag 4
#define cmdPkg_RGBCamMsg_shutdownRGBCam_tag      5
#define cmdPkg_RGBCamMsg_bootupRGBCam_tag        6
#define cmdPkg_RGBCamMsg_powerOffRGBCam_tag      7
#define cmdPkg_RGBCamMsg_powerOnRGBCam_tag       8
#define cmdPkg_RGBCamMsg_alwaysOnModeRGBCam_tag  9
#define cmdPkg_RGBCamMsg_optimizeModeRGBCam_tag  10
#define cmdPkg_RGBCamMsg_runFCCRGBCam_tag        11
#define cmdPkg_RGBCamMsg_getInfoRGBCam_tag       12
#define cmdPkg_RGBCamMsg_writeRegRGBCam_tag      13
#define cmdPkg_RGBCamMsg_readRegRGBCam_tag       14
#define cmdPkg_RGBCamMsg_videoModeRGBCam_tag     15
#define cmdPkg_RGBCamMsg_bightnessRGBCam_tag     16
#define cmdPkg_RGBCamMsg_expouseRGBCam_tag       17
#define cmdPkg_RGBCamMsg_autoGainRGBCam_tag      18
#define cmdPkg_RGBCamMsg_gainCeilingRGBCam_tag   19
#define cmdPkg_RGBCamMsg_frameRateRGBCam_tag     20
#define cmdPkg_RGBCamMsg_pixelFormatRGBCam_tag   21
#define cmdPkg_RGBCamMsg_frameSizeRGBCam_tag     22
#define cmdPkg_IRCamMsg_startIrCam_tag           1
#define cmdPkg_IRCamMsg_stopIrCam_tag            2
#define cmdPkg_IRCamMsg_captureIrCam_tag         3
#define cmdPkg_IRCamMsg_updateIntervalIrCam_tag  4
#define cmdPkg_IRCamMsg_shutdownIrCam_tag        5
#define cmdPkg_IRCamMsg_bootupIrCam_tag          6
#define cmdPkg_IRCamMsg_powerOffIrCam_tag        7
#define cmdPkg_IRCamMsg_powerOnIrCam_tag         8
#define cmdPkg_IRCamMsg_alwaysOnModeIrCam_tag    9
#define cmdPkg_IRCamMsg_optimizeModeIrCam_tag    10
#define cmdPkg_IRCamMsg_runFCCIrCam_tag          11
#define cmdPkg_IRCamMsg_getInfoIrCam_tag         12
#define cmdPkg_IRCamMsg_humanDetectionEnIrCam_tag 13
#define cmdPkg_transferControlImuMsg_dimension_tag 2
#define cmdPkg_transferControlImuMsg_quaternion_tag 3
#define cmdPkg_transferControlImuMsg_imuOmega_tag 4
#define cmdPkg_transferControlImuMsg_imuAbsoluteLinearSpeed_tag 5
#define cmdPkg_transferControlImuMsg_accel_tag   6
#define cmdPkg_transferControlImuMsg_imuPosition_tag 7
#define cmdPkg_transferControlImuMsg_angularVelocity_tag 8
#define cmdPkg_transferControlUwbMsg_location_tag 2
#define cmdPkg_transferControlUwbMsg_ranging_tag 3
#define cmdPkg_transferControlMsg_imu_tag        2
#define cmdPkg_transferControlMsg_uwb_tag        4
#define cmdPkg_cmdMsg_irMsg_tag                  1
#define cmdPkg_cmdMsg_rgbMsg_tag                 2
#define cmdPkg_cmdMsg_transferControlCfg_tag     3
#define cmdPkg_cmdMsg_transferControlGet_tag     4

/* Struct field encoding specification for nanopb */
#define cmdPkg_writeRegMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   reg,               1) \
X(a, STATIC,   SINGULAR, UINT32,   value,             2)
#define cmdPkg_writeRegMsg_CALLBACK NULL
#define cmdPkg_writeRegMsg_DEFAULT NULL

#define cmdPkg_rgbVideoModeMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   mode,              1) \
X(a, STATIC,   SINGULAR, UINT32,   frameCnt,          2)
#define cmdPkg_rgbVideoModeMsg_CALLBACK NULL
#define cmdPkg_rgbVideoModeMsg_DEFAULT NULL

#define cmdPkg_autoGainRGBCamMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   enable,            1) \
X(a, STATIC,   SINGULAR, UINT32,   gainDb,            2) \
X(a, STATIC,   SINGULAR, UINT32,   gainDbCeiling,     3)
#define cmdPkg_autoGainRGBCamMsg_CALLBACK NULL
#define cmdPkg_autoGainRGBCamMsg_DEFAULT NULL

#define cmdPkg_expouseRGBCamMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   enable,            1) \
X(a, STATIC,   SINGULAR, UINT32,   exposureUs,        2)
#define cmdPkg_expouseRGBCamMsg_CALLBACK NULL
#define cmdPkg_expouseRGBCamMsg_DEFAULT NULL

#define cmdPkg_RGBCamMsg_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT32,   (type,startRGBCam,type.startRGBCam),   1) \
X(a, STATIC,   ONEOF,    BOOL,     (type,stopRGBCam,type.stopRGBCam),   2) \
X(a, STATIC,   ONEOF,    BOOL,     (type,captureRGBCam,type.captureRGBCam),   3) \
X(a, STATIC,   ONEOF,    UINT32,   (type,updateIntervalRGBCam,type.updateIntervalRGBCam),   4) \
X(a, STATIC,   ONEOF,    BOOL,     (type,shutdownRGBCam,type.shutdownRGBCam),   5) \
X(a, STATIC,   ONEOF,    BOOL,     (type,bootupRGBCam,type.bootupRGBCam),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (type,powerOffRGBCam,type.powerOffRGBCam),   7) \
X(a, STATIC,   ONEOF,    BOOL,     (type,powerOnRGBCam,type.powerOnRGBCam),   8) \
X(a, STATIC,   ONEOF,    BOOL,     (type,alwaysOnModeRGBCam,type.alwaysOnModeRGBCam),   9) \
X(a, STATIC,   ONEOF,    BOOL,     (type,optimizeModeRGBCam,type.optimizeModeRGBCam),  10) \
X(a, STATIC,   ONEOF,    BOOL,     (type,runFCCRGBCam,type.runFCCRGBCam),  11) \
X(a, STATIC,   ONEOF,    BOOL,     (type,getInfoRGBCam,type.getInfoRGBCam),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,writeRegRGBCam,type.writeRegRGBCam),  13) \
X(a, STATIC,   ONEOF,    UINT32,   (type,readRegRGBCam,type.readRegRGBCam),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,videoModeRGBCam,type.videoModeRGBCam),  15) \
X(a, STATIC,   ONEOF,    UINT32,   (type,bightnessRGBCam,type.bightnessRGBCam),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,expouseRGBCam,type.expouseRGBCam),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,autoGainRGBCam,type.autoGainRGBCam),  18) \
X(a, STATIC,   ONEOF,    UINT32,   (type,gainCeilingRGBCam,type.gainCeilingRGBCam),  19) \
X(a, STATIC,   ONEOF,    UINT32,   (type,frameRateRGBCam,type.frameRateRGBCam),  20) \
X(a, STATIC,   ONEOF,    UINT32,   (type,pixelFormatRGBCam,type.pixelFormatRGBCam),  21) \
X(a, STATIC,   ONEOF,    UINT32,   (type,frameSizeRGBCam,type.frameSizeRGBCam),  22)
#define cmdPkg_RGBCamMsg_CALLBACK NULL
#define cmdPkg_RGBCamMsg_DEFAULT NULL
#define cmdPkg_RGBCamMsg_type_writeRegRGBCam_MSGTYPE cmdPkg_writeRegMsg
#define cmdPkg_RGBCamMsg_type_videoModeRGBCam_MSGTYPE cmdPkg_rgbVideoModeMsg
#define cmdPkg_RGBCamMsg_type_expouseRGBCam_MSGTYPE cmdPkg_expouseRGBCamMsg
#define cmdPkg_RGBCamMsg_type_autoGainRGBCam_MSGTYPE cmdPkg_autoGainRGBCamMsg

#define cmdPkg_IRCamMsg_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT32,   (type,startIrCam,type.startIrCam),   1) \
X(a, STATIC,   ONEOF,    BOOL,     (type,stopIrCam,type.stopIrCam),   2) \
X(a, STATIC,   ONEOF,    BOOL,     (type,captureIrCam,type.captureIrCam),   3) \
X(a, STATIC,   ONEOF,    UINT32,   (type,updateIntervalIrCam,type.updateIntervalIrCam),   4) \
X(a, STATIC,   ONEOF,    BOOL,     (type,shutdownIrCam,type.shutdownIrCam),   5) \
X(a, STATIC,   ONEOF,    BOOL,     (type,bootupIrCam,type.bootupIrCam),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (type,powerOffIrCam,type.powerOffIrCam),   7) \
X(a, STATIC,   ONEOF,    BOOL,     (type,powerOnIrCam,type.powerOnIrCam),   8) \
X(a, STATIC,   ONEOF,    BOOL,     (type,alwaysOnModeIrCam,type.alwaysOnModeIrCam),   9) \
X(a, STATIC,   ONEOF,    BOOL,     (type,optimizeModeIrCam,type.optimizeModeIrCam),  10) \
X(a, STATIC,   ONEOF,    BOOL,     (type,runFCCIrCam,type.runFCCIrCam),  11) \
X(a, STATIC,   ONEOF,    BOOL,     (type,getInfoIrCam,type.getInfoIrCam),  12) \
X(a, STATIC,   ONEOF,    BOOL,     (type,humanDetectionEnIrCam,type.humanDetectionEnIrCam),  13)
#define cmdPkg_IRCamMsg_CALLBACK NULL
#define cmdPkg_IRCamMsg_DEFAULT NULL

#define cmdPkg_transferControlImuMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     dimension,         2) \
X(a, STATIC,   SINGULAR, BOOL,     quaternion,        3) \
X(a, STATIC,   SINGULAR, BOOL,     imuOmega,          4) \
X(a, STATIC,   SINGULAR, BOOL,     imuAbsoluteLinearSpeed,   5) \
X(a, STATIC,   SINGULAR, BOOL,     accel,             6) \
X(a, STATIC,   SINGULAR, BOOL,     imuPosition,       7) \
X(a, STATIC,   SINGULAR, BOOL,     angularVelocity,   8)
#define cmdPkg_transferControlImuMsg_CALLBACK NULL
#define cmdPkg_transferControlImuMsg_DEFAULT NULL

#define cmdPkg_transferControlUwbMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     location,          2) \
X(a, STATIC,   SINGULAR, BOOL,     ranging,           3)
#define cmdPkg_transferControlUwbMsg_CALLBACK NULL
#define cmdPkg_transferControlUwbMsg_DEFAULT NULL

#define cmdPkg_transferControlMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  imu,               2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uwb,               4)
#define cmdPkg_transferControlMsg_CALLBACK NULL
#define cmdPkg_transferControlMsg_DEFAULT NULL
#define cmdPkg_transferControlMsg_imu_MSGTYPE cmdPkg_transferControlImuMsg
#define cmdPkg_transferControlMsg_uwb_MSGTYPE cmdPkg_transferControlUwbMsg

#define cmdPkg_cmdMsg_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,irMsg,type.irMsg),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,rgbMsg,type.rgbMsg),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,transferControlCfg,type.transferControlCfg),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (type,transferControlGet,type.transferControlGet),   4)
#define cmdPkg_cmdMsg_CALLBACK NULL
#define cmdPkg_cmdMsg_DEFAULT NULL
#define cmdPkg_cmdMsg_type_irMsg_MSGTYPE cmdPkg_IRCamMsg
#define cmdPkg_cmdMsg_type_rgbMsg_MSGTYPE cmdPkg_RGBCamMsg
#define cmdPkg_cmdMsg_type_transferControlCfg_MSGTYPE cmdPkg_transferControlMsg

extern const pb_msgdesc_t cmdPkg_writeRegMsg_msg;
extern const pb_msgdesc_t cmdPkg_rgbVideoModeMsg_msg;
extern const pb_msgdesc_t cmdPkg_autoGainRGBCamMsg_msg;
extern const pb_msgdesc_t cmdPkg_expouseRGBCamMsg_msg;
extern const pb_msgdesc_t cmdPkg_RGBCamMsg_msg;
extern const pb_msgdesc_t cmdPkg_IRCamMsg_msg;
extern const pb_msgdesc_t cmdPkg_transferControlImuMsg_msg;
extern const pb_msgdesc_t cmdPkg_transferControlUwbMsg_msg;
extern const pb_msgdesc_t cmdPkg_transferControlMsg_msg;
extern const pb_msgdesc_t cmdPkg_cmdMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmdPkg_writeRegMsg_fields &cmdPkg_writeRegMsg_msg
#define cmdPkg_rgbVideoModeMsg_fields &cmdPkg_rgbVideoModeMsg_msg
#define cmdPkg_autoGainRGBCamMsg_fields &cmdPkg_autoGainRGBCamMsg_msg
#define cmdPkg_expouseRGBCamMsg_fields &cmdPkg_expouseRGBCamMsg_msg
#define cmdPkg_RGBCamMsg_fields &cmdPkg_RGBCamMsg_msg
#define cmdPkg_IRCamMsg_fields &cmdPkg_IRCamMsg_msg
#define cmdPkg_transferControlImuMsg_fields &cmdPkg_transferControlImuMsg_msg
#define cmdPkg_transferControlUwbMsg_fields &cmdPkg_transferControlUwbMsg_msg
#define cmdPkg_transferControlMsg_fields &cmdPkg_transferControlMsg_msg
#define cmdPkg_cmdMsg_fields &cmdPkg_cmdMsg_msg

/* Maximum encoded size of messages (where known) */
#define cmdPkg_IRCamMsg_size                     6
#define cmdPkg_RGBCamMsg_size                    21
#define cmdPkg_autoGainRGBCamMsg_size            18
#define cmdPkg_cmdMsg_size                       24
#define cmdPkg_expouseRGBCamMsg_size             12
#define cmdPkg_rgbVideoModeMsg_size              12
#define cmdPkg_transferControlImuMsg_size        14
#define cmdPkg_transferControlMsg_size           22
#define cmdPkg_transferControlUwbMsg_size        4
#define cmdPkg_writeRegMsg_size                  12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
