/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "command.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmdPkg_writeRegMsg, cmdPkg_writeRegMsg, AUTO)


PB_BIND(cmdPkg_rgbVideoModeMsg, cmdPkg_rgbVideoModeMsg, AUTO)


PB_BIND(cmdPkg_autoGainRGBCamMsg, cmdPkg_autoGainRGBCamMsg, AUTO)


PB_BIND(cmdPkg_expouseRGBCamMsg, cmdPkg_expouseRGBCamMsg, AUTO)


PB_BIND(cmdPkg_RGBCamMsg, cmdPkg_RGBCamMsg, AUTO)


PB_BIND(cmdPkg_IRCamMsg, cmdPkg_IRCamMsg, AUTO)


PB_BIND(cmdPkg_transferControlImuMsg, cmdPkg_transferControlImuMsg, AUTO)


PB_BIND(cmdPkg_transferControlUwbMsg, cmdPkg_transferControlUwbMsg, AUTO)


PB_BIND(cmdPkg_transferControlMsg, cmdPkg_transferControlMsg, AUTO)


PB_BIND(cmdPkg_cmdMsg, cmdPkg_cmdMsg, AUTO)



