/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "file-transfer.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fileTransferPkg_fileDataMsg, fileTransferPkg_fileDataMsg, AUTO)


PB_BIND(fileTransferPkg_getFileMsg, fileTransferPkg_getFileMsg, AUTO)


PB_BIND(fileTransferPkg_fileInfo, fileTransferPkg_fileInfo, AUTO)


PB_BIND(fileTransferPkg_listFilesMsg, fileTransferPkg_listFilesMsg, AUTO)


PB_BIND(fileTransferPkg_delFilesMsg, fileTransferPkg_delFilesMsg, AUTO)


PB_BIND(fileTransferPkg_fileMsg, fileTransferPkg_fileMsg, AUTO)





