/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "hw_logger.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HwLogPkg_SystemFault, HwLogPkg_SystemFault, AUTO)


PB_BIND(HwLogPkg_Watchdog, HwLogPkg_Watchdog, AUTO)


PB_BIND(HwLogPkg_Entry, HwLogPkg_Entry, 2)


PB_BIND(HwLogPkg_Timestamp, HwLogPkg_Timestamp, AUTO)


PB_BIND(HwLogPkg_Debug, HwLogPkg_Debug, AUTO)





