/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "navigation.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(navigationPkg_paramMsg, navigationPkg_paramMsg, AUTO)


PB_BIND(navigationPkg_cordinate, navigationPkg_cordinate, AUTO)


PB_BIND(navigationPkg_target, navigationPkg_target, AUTO)


PB_BIND(navigationPkg_seeking, navigationPkg_seeking, AUTO)


PB_BIND(navigationPkg_position, navigationPkg_position, AUTO)


PB_BIND(navigationPkg_autoNav, navigationPkg_autoNav, AUTO)


PB_BIND(navigationPkg_levyStatus, navigationPkg_levyStatus, AUTO)


PB_BIND(navigationPkg_navigationMsg, navigationPkg_navigationMsg, AUTO)





