/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "sensor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sensorPkg_channelConfigMsg, sensorPkg_channelConfigMsg, AUTO)


PB_BIND(sensorPkg_channelsConfigMsg, sensorPkg_channelsConfigMsg, AUTO)


PB_BIND(sensorPkg_position, sensorPkg_position, AUTO)


PB_BIND(sensorPkg_vectorChannel, sensorPkg_vectorChannel, AUTO)


PB_BIND(sensorPkg_beacon, sensorPkg_beacon, AUTO)


PB_BIND(sensorPkg_quaternion, sensorPkg_quaternion, AUTO)


PB_BIND(sensorPkg_fusionMsg, sensorPkg_fusionMsg, AUTO)


PB_BIND(sensorPkg_positionMsg, sensorPkg_positionMsg, AUTO)


PB_BIND(sensorPkg_stimulationCommand, sensorPkg_stimulationCommand, AUTO)


PB_BIND(sensorPkg_devInfo, sensorPkg_devInfo, AUTO)


PB_BIND(sensorPkg_sensorMsg, sensorPkg_sensorMsg, AUTO)



