/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "stimulation.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(stimulationPkg_channelConfigMsg, stimulationPkg_channelConfigMsg, AUTO)


PB_BIND(stimulationPkg_burstMsg, stimulationPkg_burstMsg, AUTO)


PB_BIND(stimulationPkg_channelsConfigMsg, stimulationPkg_channelsConfigMsg, AUTO)


PB_BIND(stimulationPkg_directionControlMsg, stimulationPkg_directionControlMsg, AUTO)


PB_BIND(stimulationPkg_autoStimulationMsg, stimulationPkg_autoStimulationMsg, AUTO)


PB_BIND(stimulationPkg_resetCfg, stimulationPkg_resetCfg, AUTO)


PB_BIND(stimulationPkg_stiInfo, stimulationPkg_stiInfo, AUTO)


PB_BIND(stimulationPkg_volRangeForward, stimulationPkg_volRangeForward, AUTO)


PB_BIND(stimulationPkg_volRangeForwardMsg, stimulationPkg_volRangeForwardMsg, AUTO)


PB_BIND(stimulationPkg_stimulationMsg, stimulationPkg_stimulationMsg, AUTO)




