/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "uwb-dev.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(uwbDevPkg_uwbLog, uwbDevPkg_uwbLog, AUTO)


PB_BIND(uwbDevPkg_devReq, uwbDevPkg_devReq, AUTO)


PB_BIND(uwbDevPkg_neighborInfo, uwbDevPkg_neighborInfo, AUTO)


PB_BIND(uwbDevPkg_neighborInfoList, uwbDevPkg_neighborInfoList, 2)


PB_BIND(uwbDevPkg_hostSetup, uwbDevPkg_hostSetup, 2)


PB_BIND(uwbDevPkg_neighborRangingInfo, uwbDevPkg_neighborRangingInfo, AUTO)


PB_BIND(uwbDevPkg_testMsg, uwbDevPkg_testMsg, AUTO)


PB_BIND(uwbDevPkg_testMsgResponse, uwbDevPkg_testMsgResponse, AUTO)


PB_BIND(uwbDevPkg_uwbDevInfo, uwbDevPkg_uwbDevInfo, AUTO)


PB_BIND(uwbDevPkg_uwbAncNetInfo, uwbDevPkg_uwbAncNetInfo, 2)


PB_BIND(uwbDevPkg_uwbDevNetInfo, uwbDevPkg_uwbDevNetInfo, AUTO)


PB_BIND(uwbDevPkg_uwbRangingInfo, uwbDevPkg_uwbRangingInfo, AUTO)


PB_BIND(uwbDevPkg_uwbDevMsg, uwbDevPkg_uwbDevMsg, 2)








