/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_UWBDEVPKG_UWB_DEV_PB_H_INCLUDED
#define PB_UWBDEVPKG_UWB_DEV_PB_H_INCLUDED
#include <pb.h>
#include "uwb-dev-config.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _uwbDevPkg_uwbError {
    uwbDevPkg_uwbError_UWB_OK = 0,
    uwbDevPkg_uwbError_UWB_SET_CONFIG_ERR = 1
} uwbDevPkg_uwbError;

typedef enum _uwbDevPkg_stateCode {
    uwbDevPkg_stateCode_SEARCHING = 0,
    uwbDevPkg_stateCode_CONNECTED = 1
} uwbDevPkg_stateCode;

typedef enum _uwbDevPkg_neighborStateCode {
    uwbDevPkg_neighborStateCode_IN_RANGE = 0, /* uwb in list that is active, in range, and are slotted to range with */
    uwbDevPkg_neighborStateCode_OUT_OF_RANGE = 1, /* uwb in list that is active, out of range, and a neighbor is slotted to range with */
    uwbDevPkg_neighborStateCode_INACTIVE = 2 /* uwb in list that is not active (could have previously been neighbor, hidden, or twice hidden) */
} uwbDevPkg_neighborStateCode;

typedef enum _uwbDevPkg_actionReq {
    uwbDevPkg_actionReq_ACTION_UNKNOW = 0,
    uwbDevPkg_actionReq_GET_DEV_CFG = 1,
    uwbDevPkg_actionReq_GET_DEV_NET_INFO = 2,
    uwbDevPkg_actionReq_GET_DEV_INFO = 3,
    uwbDevPkg_actionReq_SET_DEV_CFG = 4
} uwbDevPkg_actionReq;

typedef enum _uwbDevPkg_rangingError {
    uwbDevPkg_rangingError_APP_UWB_SUCCESS = 0,
    /* Ranging error */
    uwbDevPkg_rangingError_APP_UWB_WAIT_CONFIRM_TIMEOUT = 1,
    uwbDevPkg_rangingError_APP_UWB_RX_TIMEOUT = 2,
    uwbDevPkg_rangingError_APP_UWB_POLL_TIMEOUT = 3,
    uwbDevPkg_rangingError_APP_UWB_FINAL_TIMEOUT = 4,
    uwbDevPkg_rangingError_APP_UWB_UNKNOWN = 5
} uwbDevPkg_rangingError;

/* Struct definitions */
typedef struct _uwbDevPkg_uwbLog {
    pb_callback_t msg;
} uwbDevPkg_uwbLog;

typedef struct _uwbDevPkg_devReq {
    uwbDevPkg_actionReq action;
    uint32_t address;
} uwbDevPkg_devReq;

typedef struct _uwbDevPkg_neighborInfo {
    uint32_t address;
    bool has_position;
    uwbDevPkg_uwbPos position;
} uwbDevPkg_neighborInfo;

typedef struct _uwbDevPkg_neighborInfoList {
    uint32_t address;
    pb_size_t neighbors_count;
    uint32_t neighbors[100];
} uwbDevPkg_neighborInfoList;

typedef struct _uwbDevPkg_hostSetup {
    uint32_t address;
    pb_size_t neighbors_count;
    uint32_t neighbors[100];
} uwbDevPkg_hostSetup;

typedef struct _uwbDevPkg_neighborRangingInfo {
    uint32_t address;
    float distance_rsl;
    uwbDevPkg_rangingError error;
    uwbDevPkg_neighborStateCode state;
} uwbDevPkg_neighborRangingInfo;

typedef struct _uwbDevPkg_testMsg {
    uint32_t code;
    pb_size_t ping_count;
    uint32_t ping[25];
} uwbDevPkg_testMsg;

typedef struct _uwbDevPkg_testMsgResponse {
    uint32_t code;
    bool success;
} uwbDevPkg_testMsgResponse;

/* ******************************************************************************
   COMMON DEVICE INFO
****************************************************************************** */
typedef struct _uwbDevPkg_uwbDevInfo {
    uwbDevPkg_OpModeCode opMode;
    uint32_t address;
    bool has_position;
    uwbDevPkg_uwbPos position;
    uwbDevPkg_stateCode state;
    uint32_t neighborsCount;
    uint32_t hiddensCount;
    uint32_t swMajorVersion;
    uint32_t swMinorVersion;
    uint32_t slotDurationMs;
    uint32_t panId;
    bool isInTestMode;
} uwbDevPkg_uwbDevInfo;

/* ******************************************************************************
  ANCHOR NETWORK INFO
****************************************************************************** */
typedef struct _uwbDevPkg_uwbAncNetInfo {
    uint32_t address;
    bool has_position;
    uwbDevPkg_uwbPos position;
    uwbDevPkg_OpModeCode opMode;
    uwbDevPkg_stateCode state;
    pb_size_t neighbors_count;
    uint32_t neighbors[100];
    pb_size_t hiddens_count;
    uint32_t hiddens[100];
} uwbDevPkg_uwbAncNetInfo;

/* ******************************************************************************
  DEV NETWORK INFO
****************************************************************************** */
typedef struct _uwbDevPkg_uwbDevNetInfo {
    uint32_t address;
    bool has_position;
    uwbDevPkg_uwbPos position;
    uwbDevPkg_stateCode state;
    uwbDevPkg_OpModeCode opMode;
    pb_size_t neighbors_count;
    uwbDevPkg_neighborInfo neighbors[3];
    uint32_t timestamp;
} uwbDevPkg_uwbDevNetInfo;

typedef struct _uwbDevPkg_uwbRangingInfo {
    uint32_t address;
    bool isInTestMode;
    uwbDevPkg_stateCode state;
    pb_size_t neighbors_count;
    uwbDevPkg_neighborRangingInfo neighbors[4];
} uwbDevPkg_uwbRangingInfo;

/* ******************************************************************************
  UWB DEVICE MESSENGER
****************************************************************************** */
typedef struct _uwbDevPkg_uwbDevMsg {
    pb_size_t which_type;
    union {
        uwbDevPkg_uwbLog log;
        uwbDevPkg_uwbDevConfig devConfig;
        uwbDevPkg_uwbDevInfo devInfo;
        uwbDevPkg_uwbDevNetInfo devNetInfo;
        uwbDevPkg_uwbAncNetInfo ancNetInfo;
        uwbDevPkg_uwbError uwbError;
        uwbDevPkg_uwbRangingInfo rangingInfo;
        /* Request */
        bool getDevCfg;
        bool getDevNetInfo;
        bool getDevInfo;
        uwbDevPkg_uwbDevConfig setDevCfg;
        uwbDevPkg_uwbSmoothAlgoCfg smoothAlgoCfg;
        uwbDevPkg_uwbCalibCfg setCalibCfg;
        bool getCalibInfo;
        uwbDevPkg_uwbNetworkCreateConfig netCfg;
        uwbDevPkg_uwbTestModeCfg testModeCfg;
        /* Transfer */
        bool listNeighbors;
        uwbDevPkg_neighborInfoList neighborsList;
        uwbDevPkg_testMsg testMsg;
        bool hostSetupReq;
        uwbDevPkg_hostSetup hostMsg;
        uwbDevPkg_testMsgResponse testMsgResponse;
    } type;
} uwbDevPkg_uwbDevMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _uwbDevPkg_uwbError_MIN uwbDevPkg_uwbError_UWB_OK
#define _uwbDevPkg_uwbError_MAX uwbDevPkg_uwbError_UWB_SET_CONFIG_ERR
#define _uwbDevPkg_uwbError_ARRAYSIZE ((uwbDevPkg_uwbError)(uwbDevPkg_uwbError_UWB_SET_CONFIG_ERR+1))

#define _uwbDevPkg_stateCode_MIN uwbDevPkg_stateCode_SEARCHING
#define _uwbDevPkg_stateCode_MAX uwbDevPkg_stateCode_CONNECTED
#define _uwbDevPkg_stateCode_ARRAYSIZE ((uwbDevPkg_stateCode)(uwbDevPkg_stateCode_CONNECTED+1))

#define _uwbDevPkg_neighborStateCode_MIN uwbDevPkg_neighborStateCode_IN_RANGE
#define _uwbDevPkg_neighborStateCode_MAX uwbDevPkg_neighborStateCode_INACTIVE
#define _uwbDevPkg_neighborStateCode_ARRAYSIZE ((uwbDevPkg_neighborStateCode)(uwbDevPkg_neighborStateCode_INACTIVE+1))

#define _uwbDevPkg_actionReq_MIN uwbDevPkg_actionReq_ACTION_UNKNOW
#define _uwbDevPkg_actionReq_MAX uwbDevPkg_actionReq_SET_DEV_CFG
#define _uwbDevPkg_actionReq_ARRAYSIZE ((uwbDevPkg_actionReq)(uwbDevPkg_actionReq_SET_DEV_CFG+1))

#define _uwbDevPkg_rangingError_MIN uwbDevPkg_rangingError_APP_UWB_SUCCESS
#define _uwbDevPkg_rangingError_MAX uwbDevPkg_rangingError_APP_UWB_UNKNOWN
#define _uwbDevPkg_rangingError_ARRAYSIZE ((uwbDevPkg_rangingError)(uwbDevPkg_rangingError_APP_UWB_UNKNOWN+1))


#define uwbDevPkg_devReq_action_ENUMTYPE uwbDevPkg_actionReq




#define uwbDevPkg_neighborRangingInfo_error_ENUMTYPE uwbDevPkg_rangingError
#define uwbDevPkg_neighborRangingInfo_state_ENUMTYPE uwbDevPkg_neighborStateCode



#define uwbDevPkg_uwbDevInfo_opMode_ENUMTYPE uwbDevPkg_OpModeCode
#define uwbDevPkg_uwbDevInfo_state_ENUMTYPE uwbDevPkg_stateCode

#define uwbDevPkg_uwbAncNetInfo_opMode_ENUMTYPE uwbDevPkg_OpModeCode
#define uwbDevPkg_uwbAncNetInfo_state_ENUMTYPE uwbDevPkg_stateCode

#define uwbDevPkg_uwbDevNetInfo_state_ENUMTYPE uwbDevPkg_stateCode
#define uwbDevPkg_uwbDevNetInfo_opMode_ENUMTYPE uwbDevPkg_OpModeCode

#define uwbDevPkg_uwbRangingInfo_state_ENUMTYPE uwbDevPkg_stateCode

#define uwbDevPkg_uwbDevMsg_type_uwbError_ENUMTYPE uwbDevPkg_uwbError


/* Initializer values for message structs */
#define uwbDevPkg_uwbLog_init_default            {{{NULL}, NULL}}
#define uwbDevPkg_devReq_init_default            {_uwbDevPkg_actionReq_MIN, 0}
#define uwbDevPkg_neighborInfo_init_default      {0, false, uwbDevPkg_uwbPos_init_default}
#define uwbDevPkg_neighborInfoList_init_default  {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define uwbDevPkg_hostSetup_init_default         {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define uwbDevPkg_neighborRangingInfo_init_default {0, 0, _uwbDevPkg_rangingError_MIN, _uwbDevPkg_neighborStateCode_MIN}
#define uwbDevPkg_testMsg_init_default           {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define uwbDevPkg_testMsgResponse_init_default   {0, 0}
#define uwbDevPkg_uwbDevInfo_init_default        {_uwbDevPkg_OpModeCode_MIN, 0, false, uwbDevPkg_uwbPos_init_default, _uwbDevPkg_stateCode_MIN, 0, 0, 0, 0, 0, 0, 0}
#define uwbDevPkg_uwbAncNetInfo_init_default     {0, false, uwbDevPkg_uwbPos_init_default, _uwbDevPkg_OpModeCode_MIN, _uwbDevPkg_stateCode_MIN, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define uwbDevPkg_uwbDevNetInfo_init_default     {0, false, uwbDevPkg_uwbPos_init_default, _uwbDevPkg_stateCode_MIN, _uwbDevPkg_OpModeCode_MIN, 0, {uwbDevPkg_neighborInfo_init_default, uwbDevPkg_neighborInfo_init_default, uwbDevPkg_neighborInfo_init_default}, 0}
#define uwbDevPkg_uwbRangingInfo_init_default    {0, 0, _uwbDevPkg_stateCode_MIN, 0, {uwbDevPkg_neighborRangingInfo_init_default, uwbDevPkg_neighborRangingInfo_init_default, uwbDevPkg_neighborRangingInfo_init_default, uwbDevPkg_neighborRangingInfo_init_default}}
#define uwbDevPkg_uwbDevMsg_init_default         {0, {uwbDevPkg_uwbLog_init_default}}
#define uwbDevPkg_uwbLog_init_zero               {{{NULL}, NULL}}
#define uwbDevPkg_devReq_init_zero               {_uwbDevPkg_actionReq_MIN, 0}
#define uwbDevPkg_neighborInfo_init_zero         {0, false, uwbDevPkg_uwbPos_init_zero}
#define uwbDevPkg_neighborInfoList_init_zero     {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define uwbDevPkg_hostSetup_init_zero            {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define uwbDevPkg_neighborRangingInfo_init_zero  {0, 0, _uwbDevPkg_rangingError_MIN, _uwbDevPkg_neighborStateCode_MIN}
#define uwbDevPkg_testMsg_init_zero              {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define uwbDevPkg_testMsgResponse_init_zero      {0, 0}
#define uwbDevPkg_uwbDevInfo_init_zero           {_uwbDevPkg_OpModeCode_MIN, 0, false, uwbDevPkg_uwbPos_init_zero, _uwbDevPkg_stateCode_MIN, 0, 0, 0, 0, 0, 0, 0}
#define uwbDevPkg_uwbAncNetInfo_init_zero        {0, false, uwbDevPkg_uwbPos_init_zero, _uwbDevPkg_OpModeCode_MIN, _uwbDevPkg_stateCode_MIN, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define uwbDevPkg_uwbDevNetInfo_init_zero        {0, false, uwbDevPkg_uwbPos_init_zero, _uwbDevPkg_stateCode_MIN, _uwbDevPkg_OpModeCode_MIN, 0, {uwbDevPkg_neighborInfo_init_zero, uwbDevPkg_neighborInfo_init_zero, uwbDevPkg_neighborInfo_init_zero}, 0}
#define uwbDevPkg_uwbRangingInfo_init_zero       {0, 0, _uwbDevPkg_stateCode_MIN, 0, {uwbDevPkg_neighborRangingInfo_init_zero, uwbDevPkg_neighborRangingInfo_init_zero, uwbDevPkg_neighborRangingInfo_init_zero, uwbDevPkg_neighborRangingInfo_init_zero}}
#define uwbDevPkg_uwbDevMsg_init_zero            {0, {uwbDevPkg_uwbLog_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define uwbDevPkg_uwbLog_msg_tag                 1
#define uwbDevPkg_devReq_action_tag              1
#define uwbDevPkg_devReq_address_tag             2
#define uwbDevPkg_neighborInfo_address_tag       1
#define uwbDevPkg_neighborInfo_position_tag      2
#define uwbDevPkg_neighborInfoList_address_tag   1
#define uwbDevPkg_neighborInfoList_neighbors_tag 2
#define uwbDevPkg_hostSetup_address_tag          1
#define uwbDevPkg_hostSetup_neighbors_tag        2
#define uwbDevPkg_neighborRangingInfo_address_tag 1
#define uwbDevPkg_neighborRangingInfo_distance_rsl_tag 2
#define uwbDevPkg_neighborRangingInfo_error_tag  3
#define uwbDevPkg_neighborRangingInfo_state_tag  4
#define uwbDevPkg_testMsg_code_tag               1
#define uwbDevPkg_testMsg_ping_tag               2
#define uwbDevPkg_testMsgResponse_code_tag       1
#define uwbDevPkg_testMsgResponse_success_tag    2
#define uwbDevPkg_uwbDevInfo_opMode_tag          1
#define uwbDevPkg_uwbDevInfo_address_tag         2
#define uwbDevPkg_uwbDevInfo_position_tag        3
#define uwbDevPkg_uwbDevInfo_state_tag           4
#define uwbDevPkg_uwbDevInfo_neighborsCount_tag  5
#define uwbDevPkg_uwbDevInfo_hiddensCount_tag    6
#define uwbDevPkg_uwbDevInfo_swMajorVersion_tag  7
#define uwbDevPkg_uwbDevInfo_swMinorVersion_tag  8
#define uwbDevPkg_uwbDevInfo_slotDurationMs_tag  9
#define uwbDevPkg_uwbDevInfo_panId_tag           10
#define uwbDevPkg_uwbDevInfo_isInTestMode_tag    11
#define uwbDevPkg_uwbAncNetInfo_address_tag      1
#define uwbDevPkg_uwbAncNetInfo_position_tag     2
#define uwbDevPkg_uwbAncNetInfo_opMode_tag       3
#define uwbDevPkg_uwbAncNetInfo_state_tag        4
#define uwbDevPkg_uwbAncNetInfo_neighbors_tag    5
#define uwbDevPkg_uwbAncNetInfo_hiddens_tag      6
#define uwbDevPkg_uwbDevNetInfo_address_tag      1
#define uwbDevPkg_uwbDevNetInfo_position_tag     2
#define uwbDevPkg_uwbDevNetInfo_state_tag        3
#define uwbDevPkg_uwbDevNetInfo_opMode_tag       4
#define uwbDevPkg_uwbDevNetInfo_neighbors_tag    5
#define uwbDevPkg_uwbDevNetInfo_timestamp_tag    6
#define uwbDevPkg_uwbRangingInfo_address_tag     1
#define uwbDevPkg_uwbRangingInfo_isInTestMode_tag 2
#define uwbDevPkg_uwbRangingInfo_state_tag       3
#define uwbDevPkg_uwbRangingInfo_neighbors_tag   4
#define uwbDevPkg_uwbDevMsg_log_tag              1
#define uwbDevPkg_uwbDevMsg_devConfig_tag        2
#define uwbDevPkg_uwbDevMsg_devInfo_tag          3
#define uwbDevPkg_uwbDevMsg_devNetInfo_tag       4
#define uwbDevPkg_uwbDevMsg_ancNetInfo_tag       5
#define uwbDevPkg_uwbDevMsg_uwbError_tag         6
#define uwbDevPkg_uwbDevMsg_rangingInfo_tag      7
#define uwbDevPkg_uwbDevMsg_getDevCfg_tag        21
#define uwbDevPkg_uwbDevMsg_getDevNetInfo_tag    22
#define uwbDevPkg_uwbDevMsg_getDevInfo_tag       23
#define uwbDevPkg_uwbDevMsg_setDevCfg_tag        24
#define uwbDevPkg_uwbDevMsg_smoothAlgoCfg_tag    25
#define uwbDevPkg_uwbDevMsg_setCalibCfg_tag      26
#define uwbDevPkg_uwbDevMsg_getCalibInfo_tag     27
#define uwbDevPkg_uwbDevMsg_netCfg_tag           28
#define uwbDevPkg_uwbDevMsg_testModeCfg_tag      29
#define uwbDevPkg_uwbDevMsg_listNeighbors_tag    41
#define uwbDevPkg_uwbDevMsg_neighborsList_tag    42
#define uwbDevPkg_uwbDevMsg_testMsg_tag          43
#define uwbDevPkg_uwbDevMsg_hostSetupReq_tag     44
#define uwbDevPkg_uwbDevMsg_hostMsg_tag          45
#define uwbDevPkg_uwbDevMsg_testMsgResponse_tag  46

/* Struct field encoding specification for nanopb */
#define uwbDevPkg_uwbLog_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   msg,               1)
#define uwbDevPkg_uwbLog_CALLBACK pb_default_field_callback
#define uwbDevPkg_uwbLog_DEFAULT NULL

#define uwbDevPkg_devReq_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, STATIC,   SINGULAR, UINT32,   address,           2)
#define uwbDevPkg_devReq_CALLBACK NULL
#define uwbDevPkg_devReq_DEFAULT NULL

#define uwbDevPkg_neighborInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   address,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          2)
#define uwbDevPkg_neighborInfo_CALLBACK NULL
#define uwbDevPkg_neighborInfo_DEFAULT NULL
#define uwbDevPkg_neighborInfo_position_MSGTYPE uwbDevPkg_uwbPos

#define uwbDevPkg_neighborInfoList_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   address,           1) \
X(a, STATIC,   REPEATED, UINT32,   neighbors,         2)
#define uwbDevPkg_neighborInfoList_CALLBACK NULL
#define uwbDevPkg_neighborInfoList_DEFAULT NULL

#define uwbDevPkg_hostSetup_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   address,           1) \
X(a, STATIC,   REPEATED, UINT32,   neighbors,         2)
#define uwbDevPkg_hostSetup_CALLBACK NULL
#define uwbDevPkg_hostSetup_DEFAULT NULL

#define uwbDevPkg_neighborRangingInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   address,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    distance_rsl,      2) \
X(a, STATIC,   SINGULAR, UENUM,    error,             3) \
X(a, STATIC,   SINGULAR, UENUM,    state,             4)
#define uwbDevPkg_neighborRangingInfo_CALLBACK NULL
#define uwbDevPkg_neighborRangingInfo_DEFAULT NULL

#define uwbDevPkg_testMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   code,              1) \
X(a, STATIC,   REPEATED, UINT32,   ping,              2)
#define uwbDevPkg_testMsg_CALLBACK NULL
#define uwbDevPkg_testMsg_DEFAULT NULL

#define uwbDevPkg_testMsgResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   code,              1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2)
#define uwbDevPkg_testMsgResponse_CALLBACK NULL
#define uwbDevPkg_testMsgResponse_DEFAULT NULL

#define uwbDevPkg_uwbDevInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    opMode,            1) \
X(a, STATIC,   SINGULAR, UINT32,   address,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          3) \
X(a, STATIC,   SINGULAR, UENUM,    state,             4) \
X(a, STATIC,   SINGULAR, UINT32,   neighborsCount,    5) \
X(a, STATIC,   SINGULAR, UINT32,   hiddensCount,      6) \
X(a, STATIC,   SINGULAR, UINT32,   swMajorVersion,    7) \
X(a, STATIC,   SINGULAR, UINT32,   swMinorVersion,    8) \
X(a, STATIC,   SINGULAR, UINT32,   slotDurationMs,    9) \
X(a, STATIC,   SINGULAR, UINT32,   panId,            10) \
X(a, STATIC,   SINGULAR, BOOL,     isInTestMode,     11)
#define uwbDevPkg_uwbDevInfo_CALLBACK NULL
#define uwbDevPkg_uwbDevInfo_DEFAULT NULL
#define uwbDevPkg_uwbDevInfo_position_MSGTYPE uwbDevPkg_uwbPos

#define uwbDevPkg_uwbAncNetInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   address,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          2) \
X(a, STATIC,   SINGULAR, UENUM,    opMode,            3) \
X(a, STATIC,   SINGULAR, UENUM,    state,             4) \
X(a, STATIC,   REPEATED, UINT32,   neighbors,         5) \
X(a, STATIC,   REPEATED, UINT32,   hiddens,           6)
#define uwbDevPkg_uwbAncNetInfo_CALLBACK NULL
#define uwbDevPkg_uwbAncNetInfo_DEFAULT NULL
#define uwbDevPkg_uwbAncNetInfo_position_MSGTYPE uwbDevPkg_uwbPos

#define uwbDevPkg_uwbDevNetInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   address,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          2) \
X(a, STATIC,   SINGULAR, UENUM,    state,             3) \
X(a, STATIC,   SINGULAR, UENUM,    opMode,            4) \
X(a, STATIC,   REPEATED, MESSAGE,  neighbors,         5) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         6)
#define uwbDevPkg_uwbDevNetInfo_CALLBACK NULL
#define uwbDevPkg_uwbDevNetInfo_DEFAULT NULL
#define uwbDevPkg_uwbDevNetInfo_position_MSGTYPE uwbDevPkg_uwbPos
#define uwbDevPkg_uwbDevNetInfo_neighbors_MSGTYPE uwbDevPkg_neighborInfo

#define uwbDevPkg_uwbRangingInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   address,           1) \
X(a, STATIC,   SINGULAR, BOOL,     isInTestMode,      2) \
X(a, STATIC,   SINGULAR, UENUM,    state,             3) \
X(a, STATIC,   REPEATED, MESSAGE,  neighbors,         4)
#define uwbDevPkg_uwbRangingInfo_CALLBACK NULL
#define uwbDevPkg_uwbRangingInfo_DEFAULT NULL
#define uwbDevPkg_uwbRangingInfo_neighbors_MSGTYPE uwbDevPkg_neighborRangingInfo

#define uwbDevPkg_uwbDevMsg_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,log,type.log),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,devConfig,type.devConfig),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,devInfo,type.devInfo),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,devNetInfo,type.devNetInfo),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,ancNetInfo,type.ancNetInfo),   5) \
X(a, STATIC,   ONEOF,    UENUM,    (type,uwbError,type.uwbError),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,rangingInfo,type.rangingInfo),   7) \
X(a, STATIC,   ONEOF,    BOOL,     (type,getDevCfg,type.getDevCfg),  21) \
X(a, STATIC,   ONEOF,    BOOL,     (type,getDevNetInfo,type.getDevNetInfo),  22) \
X(a, STATIC,   ONEOF,    BOOL,     (type,getDevInfo,type.getDevInfo),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,setDevCfg,type.setDevCfg),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,smoothAlgoCfg,type.smoothAlgoCfg),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,setCalibCfg,type.setCalibCfg),  26) \
X(a, STATIC,   ONEOF,    BOOL,     (type,getCalibInfo,type.getCalibInfo),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,netCfg,type.netCfg),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,testModeCfg,type.testModeCfg),  29) \
X(a, STATIC,   ONEOF,    BOOL,     (type,listNeighbors,type.listNeighbors),  41) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,neighborsList,type.neighborsList),  42) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,testMsg,type.testMsg),  43) \
X(a, STATIC,   ONEOF,    BOOL,     (type,hostSetupReq,type.hostSetupReq),  44) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,hostMsg,type.hostMsg),  45) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,testMsgResponse,type.testMsgResponse),  46)
#define uwbDevPkg_uwbDevMsg_CALLBACK NULL
#define uwbDevPkg_uwbDevMsg_DEFAULT NULL
#define uwbDevPkg_uwbDevMsg_type_log_MSGTYPE uwbDevPkg_uwbLog
#define uwbDevPkg_uwbDevMsg_type_devConfig_MSGTYPE uwbDevPkg_uwbDevConfig
#define uwbDevPkg_uwbDevMsg_type_devInfo_MSGTYPE uwbDevPkg_uwbDevInfo
#define uwbDevPkg_uwbDevMsg_type_devNetInfo_MSGTYPE uwbDevPkg_uwbDevNetInfo
#define uwbDevPkg_uwbDevMsg_type_ancNetInfo_MSGTYPE uwbDevPkg_uwbAncNetInfo
#define uwbDevPkg_uwbDevMsg_type_rangingInfo_MSGTYPE uwbDevPkg_uwbRangingInfo
#define uwbDevPkg_uwbDevMsg_type_setDevCfg_MSGTYPE uwbDevPkg_uwbDevConfig
#define uwbDevPkg_uwbDevMsg_type_smoothAlgoCfg_MSGTYPE uwbDevPkg_uwbSmoothAlgoCfg
#define uwbDevPkg_uwbDevMsg_type_setCalibCfg_MSGTYPE uwbDevPkg_uwbCalibCfg
#define uwbDevPkg_uwbDevMsg_type_netCfg_MSGTYPE uwbDevPkg_uwbNetworkCreateConfig
#define uwbDevPkg_uwbDevMsg_type_testModeCfg_MSGTYPE uwbDevPkg_uwbTestModeCfg
#define uwbDevPkg_uwbDevMsg_type_neighborsList_MSGTYPE uwbDevPkg_neighborInfoList
#define uwbDevPkg_uwbDevMsg_type_testMsg_MSGTYPE uwbDevPkg_testMsg
#define uwbDevPkg_uwbDevMsg_type_hostMsg_MSGTYPE uwbDevPkg_hostSetup
#define uwbDevPkg_uwbDevMsg_type_testMsgResponse_MSGTYPE uwbDevPkg_testMsgResponse

extern const pb_msgdesc_t uwbDevPkg_uwbLog_msg;
extern const pb_msgdesc_t uwbDevPkg_devReq_msg;
extern const pb_msgdesc_t uwbDevPkg_neighborInfo_msg;
extern const pb_msgdesc_t uwbDevPkg_neighborInfoList_msg;
extern const pb_msgdesc_t uwbDevPkg_hostSetup_msg;
extern const pb_msgdesc_t uwbDevPkg_neighborRangingInfo_msg;
extern const pb_msgdesc_t uwbDevPkg_testMsg_msg;
extern const pb_msgdesc_t uwbDevPkg_testMsgResponse_msg;
extern const pb_msgdesc_t uwbDevPkg_uwbDevInfo_msg;
extern const pb_msgdesc_t uwbDevPkg_uwbAncNetInfo_msg;
extern const pb_msgdesc_t uwbDevPkg_uwbDevNetInfo_msg;
extern const pb_msgdesc_t uwbDevPkg_uwbRangingInfo_msg;
extern const pb_msgdesc_t uwbDevPkg_uwbDevMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define uwbDevPkg_uwbLog_fields &uwbDevPkg_uwbLog_msg
#define uwbDevPkg_devReq_fields &uwbDevPkg_devReq_msg
#define uwbDevPkg_neighborInfo_fields &uwbDevPkg_neighborInfo_msg
#define uwbDevPkg_neighborInfoList_fields &uwbDevPkg_neighborInfoList_msg
#define uwbDevPkg_hostSetup_fields &uwbDevPkg_hostSetup_msg
#define uwbDevPkg_neighborRangingInfo_fields &uwbDevPkg_neighborRangingInfo_msg
#define uwbDevPkg_testMsg_fields &uwbDevPkg_testMsg_msg
#define uwbDevPkg_testMsgResponse_fields &uwbDevPkg_testMsgResponse_msg
#define uwbDevPkg_uwbDevInfo_fields &uwbDevPkg_uwbDevInfo_msg
#define uwbDevPkg_uwbAncNetInfo_fields &uwbDevPkg_uwbAncNetInfo_msg
#define uwbDevPkg_uwbDevNetInfo_fields &uwbDevPkg_uwbDevNetInfo_msg
#define uwbDevPkg_uwbRangingInfo_fields &uwbDevPkg_uwbRangingInfo_msg
#define uwbDevPkg_uwbDevMsg_fields &uwbDevPkg_uwbDevMsg_msg

/* Maximum encoded size of messages (where known) */
/* uwbDevPkg_uwbLog_size depends on runtime parameters */
/* uwbDevPkg_uwbDevMsg_size depends on runtime parameters */
#define uwbDevPkg_devReq_size                    8
#define uwbDevPkg_hostSetup_size                 606
#define uwbDevPkg_neighborInfoList_size          606
#define uwbDevPkg_neighborInfo_size              23
#define uwbDevPkg_neighborRangingInfo_size       15
#define uwbDevPkg_testMsgResponse_size           8
#define uwbDevPkg_testMsg_size                   156
#define uwbDevPkg_uwbAncNetInfo_size             1227
#define uwbDevPkg_uwbDevInfo_size                65
#define uwbDevPkg_uwbDevNetInfo_size             108
#define uwbDevPkg_uwbRangingInfo_size            78

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
