/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "uwb-dev-config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(uwbDevPkg_uwbPos, uwbDevPkg_uwbPos, AUTO)


PB_BIND(uwbDevPkg_uwbDevConfig, uwbDevPkg_uwbDevConfig, AUTO)


PB_BIND(uwbDevPkg_uwbNetworkCreateConfig, uwbDevPkg_uwbNetworkCreateConfig, AUTO)


PB_BIND(uwbDevPkg_uwbSmoothAlgoCfg, uwbDevPkg_uwbSmoothAlgoCfg, AUTO)


PB_BIND(uwbDevPkg_testNodeInfo, uwbDevPkg_testNodeInfo, AUTO)


PB_BIND(uwbDevPkg_uwbTestModeCfg, uwbDevPkg_uwbTestModeCfg, AUTO)


PB_BIND(uwbDevPkg_uwbCalibCfg, uwbDevPkg_uwbCalibCfg, AUTO)












