/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_UWBANCPKG_UWB_ANCHOR_PB_H_INCLUDED
#define PB_UWBANCPKG_UWB_ANCHOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _uwbAncPkg_uwbAncPos { 
    float x; 
    float y; 
    float z; 
} uwbAncPkg_uwbAncPos;

typedef struct _uwbAncPkg_uwbAncMsg { 
    uint32_t event; 
    uint32_t address; 
    bool has_position;
    uwbAncPkg_uwbAncPos position; 
    pb_callback_t msg; 
} uwbAncPkg_uwbAncMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define uwbAncPkg_uwbAncPos_init_default         {0, 0, 0}
#define uwbAncPkg_uwbAncMsg_init_default         {0, 0, false, uwbAncPkg_uwbAncPos_init_default, {{NULL}, NULL}}
#define uwbAncPkg_uwbAncPos_init_zero            {0, 0, 0}
#define uwbAncPkg_uwbAncMsg_init_zero            {0, 0, false, uwbAncPkg_uwbAncPos_init_zero, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define uwbAncPkg_uwbAncPos_x_tag                1
#define uwbAncPkg_uwbAncPos_y_tag                2
#define uwbAncPkg_uwbAncPos_z_tag                3
#define uwbAncPkg_uwbAncMsg_event_tag            1
#define uwbAncPkg_uwbAncMsg_address_tag          2
#define uwbAncPkg_uwbAncMsg_position_tag         3
#define uwbAncPkg_uwbAncMsg_msg_tag              4

/* Struct field encoding specification for nanopb */
#define uwbAncPkg_uwbAncPos_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define uwbAncPkg_uwbAncPos_CALLBACK NULL
#define uwbAncPkg_uwbAncPos_DEFAULT NULL

#define uwbAncPkg_uwbAncMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event,             1) \
X(a, STATIC,   SINGULAR, UINT32,   address,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          3) \
X(a, CALLBACK, SINGULAR, STRING,   msg,               4)
#define uwbAncPkg_uwbAncMsg_CALLBACK pb_default_field_callback
#define uwbAncPkg_uwbAncMsg_DEFAULT NULL
#define uwbAncPkg_uwbAncMsg_position_MSGTYPE uwbAncPkg_uwbAncPos

extern const pb_msgdesc_t uwbAncPkg_uwbAncPos_msg;
extern const pb_msgdesc_t uwbAncPkg_uwbAncMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define uwbAncPkg_uwbAncPos_fields &uwbAncPkg_uwbAncPos_msg
#define uwbAncPkg_uwbAncMsg_fields &uwbAncPkg_uwbAncMsg_msg

/* Maximum encoded size of messages (where known) */
/* uwbAncPkg_uwbAncMsg_size depends on runtime parameters */
#define uwbAncPkg_uwbAncPos_size                 15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
